### ISSUE TITLE
脚本无法运行

### ISSUE THREAD

**Issue by 10fantastic** [wjlin0/cf-lua#2]
我的2023.1月的ghub，保存不了脚本，换了2021.3的ghub，脚本又运行不了

![Uploading 屏幕截图 2023-12-05 023651.png…]()

**Comment by 10fantastic** [comment]
![Uploading 屏幕截图 2023-12-05 023651.png…]()

**Comment by 10fantastic** [comment]
![Uploading 屏幕截图 2023-12-05 023651.png…]()

**Comment by wjlin0** [comment]
哥们看不到截图

**Comment by wjlin0** [comment]
试了最新的ghub么？

**Comment by wjlin0** [comment]
> 哥们看不到截图

![image](https://github.com/wjlin0/cf-lua/assets/91306421/320516b9-50d8-42e4-9ac9-66c2deb19e5f)

**Comment by 10fantastic** [comment]
谢谢大佬，是我的ghub驱动问题，下载最新版本的ghub就可以解决了

**Comment by wjlin0** [comment]
嗯嗯
